[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs --deploy --serial --verbose"

rustflags = ["-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "info"
DEFMT_RTT_BUFFER_SIZE = "1024"
