pub mod profile_1 {

    use heapless::Vec;
    use usbd_hid::descriptor::KeyboardUsage;

    // LeftCtrl    = 0b00000001,
    // LeftShift   = 0b00000010,
    // LeftAlt     = 0b00000100,
    // LeftGui     = 0b00001000,
    // RightCtrl   = 0b00010000,
    // RightShift  = 0b00100000,
    // RightAlt    = 0b01000000,
    // RightGui    = 0x10000000,

    use crate::{
        hid_helper::keyboard_report::KeyboardReportHelper,
        io_management::{left_half_manager::LeftKeyLocation, right_half_manager::RightKeyLocation},
        profiles_management::keyboard_profile::keyboard_profile::{
            KeyAction, KeyActionSet, KeyboardProfile, UniversalKey,
        },
    };

    pub fn get_profile() -> KeyboardProfile {
        return KeyboardProfile {
            layer_key_1: UniversalKey::LeftKey(LeftKeyLocation::LT1),
            layer_key_2: UniversalKey::RightKey(RightKeyLocation::RT1),
            c1_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardTab),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c2_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardQq),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c3_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardWw),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c4_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardEe),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c5_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardRr),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c6_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardTt),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c7_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardYy),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c8_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardUu),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c9_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardIi),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c10_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardOo),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c11_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardPp),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c12_r1: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardBackslashBar),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c1_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardLeftControl),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c2_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardAa),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c3_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardSs),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c4_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardDd),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c5_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardFf),
                layer_one_action: KeyAction::HidReport(
                    Vec::from_slice(&[
                        KeyboardReportHelper::from_values(0b00001000, 0, 0, 0, 0, 0, 0),
                        KeyboardReportHelper::from_values(
                            0,
                            KeyboardUsage::KeyboardFf as u8,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ),
                        KeyboardReportHelper::from_values(
                            0,
                            KeyboardUsage::KeyboardIi as u8,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ),
                        KeyboardReportHelper::from_values(
                            0,
                            KeyboardUsage::KeyboardRr as u8,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ),
                        KeyboardReportHelper::from_values(
                            0,
                            KeyboardUsage::KeyboardEe as u8,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ),
                        KeyboardReportHelper::from_values(
                            0,
                            KeyboardUsage::KeyboardFf as u8,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ),
                        KeyboardReportHelper::from_values(
                            0,
                            KeyboardUsage::KeyboardOo as u8,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ),
                        KeyboardReportHelper::from_values(
                            0,
                            KeyboardUsage::KeyboardXx as u8,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ),
                        KeyboardReportHelper::from_values(
                            0,
                            KeyboardUsage::KeyboardEnter as u8,
                            0,
                            0,
                            0,
                            0,
                            0,
                        ),
                    ])
                    .unwrap(),
                ),
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c6_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardGg),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c7_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardHh),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c8_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardJj),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c9_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardKk),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c10_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardLl),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c11_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardSemiColon),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c12_r2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardEnter),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c1_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardLeftShift),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c2_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardZz),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c3_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardXx),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c4_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardCc),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c5_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardVv),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c6_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardBb),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c7_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardNn),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c8_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardMm),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c9_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardCommaLess),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c10_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardPeriodGreater),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c11_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardSlashQuestion),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            c12_r3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardRightShift),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            lt_1: KeyActionSet {
                base_action: KeyAction::DeadKey,
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            lt_2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardLeftGUI),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            lt_3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardLeftAlt),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            rt_1: KeyActionSet {
                base_action: KeyAction::DeadKey,
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            rt_2: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardBackspace),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
            rt_3: KeyActionSet {
                base_action: KeyAction::HidKey(KeyboardUsage::KeyboardSpacebar),
                layer_one_action: KeyAction::DeadKey,
                layer_two_action: KeyAction::DeadKey,
                layer_one_and_two_action: KeyAction::DeadKey,
            },
        };
    }
}
